#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.237
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESM.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AgendaESM")]
	public partial class AgendaESMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCitasAgenda(CitasAgenda instance);
    partial void UpdateCitasAgenda(CitasAgenda instance);
    partial void DeleteCitasAgenda(CitasAgenda instance);
    partial void InsertConsultoresAgenda(ConsultoresAgenda instance);
    partial void UpdateConsultoresAgenda(ConsultoresAgenda instance);
    partial void DeleteConsultoresAgenda(ConsultoresAgenda instance);
    partial void InsertInstitucionEducativaAgenda(InstitucionEducativaAgenda instance);
    partial void UpdateInstitucionEducativaAgenda(InstitucionEducativaAgenda instance);
    partial void DeleteInstitucionEducativaAgenda(InstitucionEducativaAgenda instance);
    partial void InsertLLamadasAgenda(LLamadasAgenda instance);
    partial void UpdateLLamadasAgenda(LLamadasAgenda instance);
    partial void DeleteLLamadasAgenda(LLamadasAgenda instance);
    #endregion
		
		public AgendaESMDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AgendaESMConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AgendaESMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgendaESMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgendaESMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgendaESMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CitasAgenda> CitasAgenda
		{
			get
			{
				return this.GetTable<CitasAgenda>();
			}
		}
		
		public System.Data.Linq.Table<ConsultoresAgenda> ConsultoresAgenda
		{
			get
			{
				return this.GetTable<ConsultoresAgenda>();
			}
		}
		
		public System.Data.Linq.Table<InstitucionEducativaAgenda> InstitucionEducativaAgenda
		{
			get
			{
				return this.GetTable<InstitucionEducativaAgenda>();
			}
		}
		
		public System.Data.Linq.Table<LLamadasAgenda> LLamadasAgenda
		{
			get
			{
				return this.GetTable<LLamadasAgenda>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Citas")]
	public partial class CitasAgenda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCita;
		
		private int _IdLLamada;
		
		private int _IdEstadoCita;
		
		private System.DateTime _FechaInicio;
		
		private System.DateTime _FechaFin;
		
		private string _Lugar;
		
		private System.Nullable<int> _IdConsultor;
		
		private string _Descripcion;
		
		private EntityRef<LLamadasAgenda> _LLamadas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCitaChanging(int value);
    partial void OnIdCitaChanged();
    partial void OnIdLLamadaChanging(int value);
    partial void OnIdLLamadaChanged();
    partial void OnIdEstadoCitaChanging(int value);
    partial void OnIdEstadoCitaChanged();
    partial void OnFechaInicioChanging(System.DateTime value);
    partial void OnFechaInicioChanged();
    partial void OnFechaFinChanging(System.DateTime value);
    partial void OnFechaFinChanged();
    partial void OnLugarChanging(string value);
    partial void OnLugarChanged();
    partial void OnIdConsultorChanging(System.Nullable<int> value);
    partial void OnIdConsultorChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public CitasAgenda()
		{
			this._LLamadas = default(EntityRef<LLamadasAgenda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCita", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCita
		{
			get
			{
				return this._IdCita;
			}
			set
			{
				if ((this._IdCita != value))
				{
					this.OnIdCitaChanging(value);
					this.SendPropertyChanging();
					this._IdCita = value;
					this.SendPropertyChanged("IdCita");
					this.OnIdCitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLLamada", DbType="Int NOT NULL")]
		public int IdLLamada
		{
			get
			{
				return this._IdLLamada;
			}
			set
			{
				if ((this._IdLLamada != value))
				{
					if (this._LLamadas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdLLamadaChanging(value);
					this.SendPropertyChanging();
					this._IdLLamada = value;
					this.SendPropertyChanged("IdLLamada");
					this.OnIdLLamadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstadoCita", DbType="Int NOT NULL")]
		public int IdEstadoCita
		{
			get
			{
				return this._IdEstadoCita;
			}
			set
			{
				if ((this._IdEstadoCita != value))
				{
					this.OnIdEstadoCitaChanging(value);
					this.SendPropertyChanging();
					this._IdEstadoCita = value;
					this.SendPropertyChanged("IdEstadoCita");
					this.OnIdEstadoCitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="DateTime NOT NULL")]
		public System.DateTime FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this.OnFechaInicioChanging(value);
					this.SendPropertyChanging();
					this._FechaInicio = value;
					this.SendPropertyChanged("FechaInicio");
					this.OnFechaInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFin", DbType="DateTime NOT NULL")]
		public System.DateTime FechaFin
		{
			get
			{
				return this._FechaFin;
			}
			set
			{
				if ((this._FechaFin != value))
				{
					this.OnFechaFinChanging(value);
					this.SendPropertyChanging();
					this._FechaFin = value;
					this.SendPropertyChanged("FechaFin");
					this.OnFechaFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lugar", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Lugar
		{
			get
			{
				return this._Lugar;
			}
			set
			{
				if ((this._Lugar != value))
				{
					this.OnLugarChanging(value);
					this.SendPropertyChanging();
					this._Lugar = value;
					this.SendPropertyChanged("Lugar");
					this.OnLugarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdConsultor", DbType="Int")]
		public System.Nullable<int> IdConsultor
		{
			get
			{
				return this._IdConsultor;
			}
			set
			{
				if ((this._IdConsultor != value))
				{
					this.OnIdConsultorChanging(value);
					this.SendPropertyChanging();
					this._IdConsultor = value;
					this.SendPropertyChanged("IdConsultor");
					this.OnIdConsultorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LLamadas_Citas", Storage="_LLamadas", ThisKey="IdLLamada", OtherKey="IdLlamada", IsForeignKey=true)]
		public LLamadasAgenda LLamadasAgenda
		{
			get
			{
				return this._LLamadas.Entity;
			}
			set
			{
				LLamadasAgenda previousValue = this._LLamadas.Entity;
				if (((previousValue != value) 
							|| (this._LLamadas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LLamadas.Entity = null;
						previousValue.CitasAgenda.Remove(this);
					}
					this._LLamadas.Entity = value;
					if ((value != null))
					{
						value.CitasAgenda.Add(this);
						this._IdLLamada = value.IdLlamada;
					}
					else
					{
						this._IdLLamada = default(int);
					}
					this.SendPropertyChanged("LLamadasAgenda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Consultores")]
	public partial class ConsultoresAgenda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdConsultor;
		
		private string _Identificacion;
		
		private string _Nombre;
		
		private string _TelefonoFijo1;
		
		private string _TelefonoFijo2;
		
		private string _TelefonoMovil1;
		
		private string _TelefonoMovil2;
		
		private string _CorreoElectronico;
		
		private EntitySet<InstitucionEducativaAgenda> _InstitucionEducativa;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdConsultorChanging(int value);
    partial void OnIdConsultorChanged();
    partial void OnIdentificacionChanging(string value);
    partial void OnIdentificacionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnTelefonoFijo1Changing(string value);
    partial void OnTelefonoFijo1Changed();
    partial void OnTelefonoFijo2Changing(string value);
    partial void OnTelefonoFijo2Changed();
    partial void OnTelefonoMovil1Changing(string value);
    partial void OnTelefonoMovil1Changed();
    partial void OnTelefonoMovil2Changing(string value);
    partial void OnTelefonoMovil2Changed();
    partial void OnCorreoElectronicoChanging(string value);
    partial void OnCorreoElectronicoChanged();
    #endregion
		
		public ConsultoresAgenda()
		{
			this._InstitucionEducativa = new EntitySet<InstitucionEducativaAgenda>(new Action<InstitucionEducativaAgenda>(this.attach_InstitucionEducativa), new Action<InstitucionEducativaAgenda>(this.detach_InstitucionEducativa));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdConsultor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdConsultor
		{
			get
			{
				return this._IdConsultor;
			}
			set
			{
				if ((this._IdConsultor != value))
				{
					this.OnIdConsultorChanging(value);
					this.SendPropertyChanging();
					this._IdConsultor = value;
					this.SendPropertyChanged("IdConsultor");
					this.OnIdConsultorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this.OnIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._Identificacion = value;
					this.SendPropertyChanged("Identificacion");
					this.OnIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoFijo1", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TelefonoFijo1
		{
			get
			{
				return this._TelefonoFijo1;
			}
			set
			{
				if ((this._TelefonoFijo1 != value))
				{
					this.OnTelefonoFijo1Changing(value);
					this.SendPropertyChanging();
					this._TelefonoFijo1 = value;
					this.SendPropertyChanged("TelefonoFijo1");
					this.OnTelefonoFijo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoFijo2", DbType="VarChar(15)")]
		public string TelefonoFijo2
		{
			get
			{
				return this._TelefonoFijo2;
			}
			set
			{
				if ((this._TelefonoFijo2 != value))
				{
					this.OnTelefonoFijo2Changing(value);
					this.SendPropertyChanging();
					this._TelefonoFijo2 = value;
					this.SendPropertyChanged("TelefonoFijo2");
					this.OnTelefonoFijo2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoMovil1", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TelefonoMovil1
		{
			get
			{
				return this._TelefonoMovil1;
			}
			set
			{
				if ((this._TelefonoMovil1 != value))
				{
					this.OnTelefonoMovil1Changing(value);
					this.SendPropertyChanging();
					this._TelefonoMovil1 = value;
					this.SendPropertyChanged("TelefonoMovil1");
					this.OnTelefonoMovil1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoMovil2", DbType="VarChar(15)")]
		public string TelefonoMovil2
		{
			get
			{
				return this._TelefonoMovil2;
			}
			set
			{
				if ((this._TelefonoMovil2 != value))
				{
					this.OnTelefonoMovil2Changing(value);
					this.SendPropertyChanging();
					this._TelefonoMovil2 = value;
					this.SendPropertyChanged("TelefonoMovil2");
					this.OnTelefonoMovil2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoElectronico", DbType="VarChar(150)")]
		public string CorreoElectronico
		{
			get
			{
				return this._CorreoElectronico;
			}
			set
			{
				if ((this._CorreoElectronico != value))
				{
					this.OnCorreoElectronicoChanging(value);
					this.SendPropertyChanging();
					this._CorreoElectronico = value;
					this.SendPropertyChanged("CorreoElectronico");
					this.OnCorreoElectronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Consultores_InstitucionEducativa", Storage="_InstitucionEducativa", ThisKey="IdConsultor", OtherKey="IdConsultor")]
		public EntitySet<InstitucionEducativaAgenda> InstitucionEducativaAgenda
		{
			get
			{
				return this._InstitucionEducativa;
			}
			set
			{
				this._InstitucionEducativa.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_InstitucionEducativa(InstitucionEducativaAgenda entity)
		{
			this.SendPropertyChanging();
			entity.ConsultoresAgenda = this;
		}
		
		private void detach_InstitucionEducativa(InstitucionEducativaAgenda entity)
		{
			this.SendPropertyChanging();
			entity.ConsultoresAgenda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InstitucionEducativa")]
	public partial class InstitucionEducativaAgenda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdIE;
		
		private System.Nullable<int> _IdConsultor;
		
		private string _CodigoDane;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Municipio;
		
		private string _Rector;
		
		private string _Email;
		
		private bool _Estado;
		
		private EntitySet<LLamadasAgenda> _LLamadas;
		
		private EntityRef<ConsultoresAgenda> _Consultores;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdIEChanging(int value);
    partial void OnIdIEChanged();
    partial void OnIdConsultorChanging(System.Nullable<int> value);
    partial void OnIdConsultorChanged();
    partial void OnCodigoDaneChanging(string value);
    partial void OnCodigoDaneChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnMunicipioChanging(string value);
    partial void OnMunicipioChanged();
    partial void OnRectorChanging(string value);
    partial void OnRectorChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnEstadoChanging(bool value);
    partial void OnEstadoChanged();
    #endregion
		
		public InstitucionEducativaAgenda()
		{
			this._LLamadas = new EntitySet<LLamadasAgenda>(new Action<LLamadasAgenda>(this.attach_LLamadas), new Action<LLamadasAgenda>(this.detach_LLamadas));
			this._Consultores = default(EntityRef<ConsultoresAgenda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdIE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdIE
		{
			get
			{
				return this._IdIE;
			}
			set
			{
				if ((this._IdIE != value))
				{
					this.OnIdIEChanging(value);
					this.SendPropertyChanging();
					this._IdIE = value;
					this.SendPropertyChanged("IdIE");
					this.OnIdIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdConsultor", DbType="Int")]
		public System.Nullable<int> IdConsultor
		{
			get
			{
				return this._IdConsultor;
			}
			set
			{
				if ((this._IdConsultor != value))
				{
					if (this._Consultores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdConsultorChanging(value);
					this.SendPropertyChanging();
					this._IdConsultor = value;
					this.SendPropertyChanged("IdConsultor");
					this.OnIdConsultorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoDane", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CodigoDane
		{
			get
			{
				return this._CodigoDane;
			}
			set
			{
				if ((this._CodigoDane != value))
				{
					this.OnCodigoDaneChanging(value);
					this.SendPropertyChanging();
					this._CodigoDane = value;
					this.SendPropertyChanged("CodigoDane");
					this.OnCodigoDaneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this.OnMunicipioChanging(value);
					this.SendPropertyChanging();
					this._Municipio = value;
					this.SendPropertyChanged("Municipio");
					this.OnMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rector", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Rector
		{
			get
			{
				return this._Rector;
			}
			set
			{
				if ((this._Rector != value))
				{
					this.OnRectorChanging(value);
					this.SendPropertyChanging();
					this._Rector = value;
					this.SendPropertyChanged("Rector");
					this.OnRectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="InstitucionEducativa_LLamadas", Storage="_LLamadas", ThisKey="IdIE", OtherKey="IdIE")]
		public EntitySet<LLamadasAgenda> LLamadasAgenda
		{
			get
			{
				return this._LLamadas;
			}
			set
			{
				this._LLamadas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Consultores_InstitucionEducativa", Storage="_Consultores", ThisKey="IdConsultor", OtherKey="IdConsultor", IsForeignKey=true)]
		public ConsultoresAgenda ConsultoresAgenda
		{
			get
			{
				return this._Consultores.Entity;
			}
			set
			{
				ConsultoresAgenda previousValue = this._Consultores.Entity;
				if (((previousValue != value) 
							|| (this._Consultores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Consultores.Entity = null;
						previousValue.InstitucionEducativaAgenda.Remove(this);
					}
					this._Consultores.Entity = value;
					if ((value != null))
					{
						value.InstitucionEducativaAgenda.Add(this);
						this._IdConsultor = value.IdConsultor;
					}
					else
					{
						this._IdConsultor = default(Nullable<int>);
					}
					this.SendPropertyChanged("ConsultoresAgenda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LLamadas(LLamadasAgenda entity)
		{
			this.SendPropertyChanging();
			entity.InstitucionEducativaAgenda = this;
		}
		
		private void detach_LLamadas(LLamadasAgenda entity)
		{
			this.SendPropertyChanging();
			entity.InstitucionEducativaAgenda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LLamadas")]
	public partial class LLamadasAgenda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdLlamada;
		
		private int _IdIE;
		
		private int _IdOperador;
		
		private int _IdEstadoLLamada;
		
		private string _Descripcion;
		
		private System.DateTime _Fecha;
		
		private EntitySet<CitasAgenda> _Citas;
		
		private EntityRef<InstitucionEducativaAgenda> _InstitucionEducativa;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLlamadaChanging(int value);
    partial void OnIdLlamadaChanged();
    partial void OnIdIEChanging(int value);
    partial void OnIdIEChanged();
    partial void OnIdOperadorChanging(int value);
    partial void OnIdOperadorChanged();
    partial void OnIdEstadoLLamadaChanging(int value);
    partial void OnIdEstadoLLamadaChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    #endregion
		
		public LLamadasAgenda()
		{
			this._Citas = new EntitySet<CitasAgenda>(new Action<CitasAgenda>(this.attach_Citas), new Action<CitasAgenda>(this.detach_Citas));
			this._InstitucionEducativa = default(EntityRef<InstitucionEducativaAgenda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLlamada", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdLlamada
		{
			get
			{
				return this._IdLlamada;
			}
			set
			{
				if ((this._IdLlamada != value))
				{
					this.OnIdLlamadaChanging(value);
					this.SendPropertyChanging();
					this._IdLlamada = value;
					this.SendPropertyChanged("IdLlamada");
					this.OnIdLlamadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdIE", DbType="Int NOT NULL")]
		public int IdIE
		{
			get
			{
				return this._IdIE;
			}
			set
			{
				if ((this._IdIE != value))
				{
					if (this._InstitucionEducativa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdIEChanging(value);
					this.SendPropertyChanging();
					this._IdIE = value;
					this.SendPropertyChanged("IdIE");
					this.OnIdIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOperador", DbType="Int NOT NULL")]
		public int IdOperador
		{
			get
			{
				return this._IdOperador;
			}
			set
			{
				if ((this._IdOperador != value))
				{
					this.OnIdOperadorChanging(value);
					this.SendPropertyChanging();
					this._IdOperador = value;
					this.SendPropertyChanged("IdOperador");
					this.OnIdOperadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstadoLLamada", DbType="Int NOT NULL")]
		public int IdEstadoLLamada
		{
			get
			{
				return this._IdEstadoLLamada;
			}
			set
			{
				if ((this._IdEstadoLLamada != value))
				{
					this.OnIdEstadoLLamadaChanging(value);
					this.SendPropertyChanging();
					this._IdEstadoLLamada = value;
					this.SendPropertyChanged("IdEstadoLLamada");
					this.OnIdEstadoLLamadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LLamadas_Citas", Storage="_Citas", ThisKey="IdLlamada", OtherKey="IdLLamada")]
		public EntitySet<CitasAgenda> CitasAgenda
		{
			get
			{
				return this._Citas;
			}
			set
			{
				this._Citas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="InstitucionEducativa_LLamadas", Storage="_InstitucionEducativa", ThisKey="IdIE", OtherKey="IdIE", IsForeignKey=true)]
		public InstitucionEducativaAgenda InstitucionEducativaAgenda
		{
			get
			{
				return this._InstitucionEducativa.Entity;
			}
			set
			{
				InstitucionEducativaAgenda previousValue = this._InstitucionEducativa.Entity;
				if (((previousValue != value) 
							|| (this._InstitucionEducativa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._InstitucionEducativa.Entity = null;
						previousValue.LLamadasAgenda.Remove(this);
					}
					this._InstitucionEducativa.Entity = value;
					if ((value != null))
					{
						value.LLamadasAgenda.Add(this);
						this._IdIE = value.IdIE;
					}
					else
					{
						this._IdIE = default(int);
					}
					this.SendPropertyChanged("InstitucionEducativaAgenda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Citas(CitasAgenda entity)
		{
			this.SendPropertyChanging();
			entity.LLamadasAgenda = this;
		}
		
		private void detach_Citas(CitasAgenda entity)
		{
			this.SendPropertyChanging();
			entity.LLamadasAgenda = null;
		}
	}
}
#pragma warning restore 1591
