<?xml version="1.0" encoding="utf-8"?><Database Name="AgendaESM" Class="AgendaESMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=XOGOST-LAPTOP\SQLEXPRESS2008r2;Initial Catalog=AgendaESM;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AgendaESMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Citas" Member="CitasAgenda">
    <Type Name="CitasAgenda">
      <Column Name="IdCita" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdLLamada" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEstadoCita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaInicio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaFin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Lugar" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IdConsultor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="LLamadas_Citas" Member="LLamadasAgenda" Storage="_LLamadas" ThisKey="IdLLamada" OtherKey="IdLlamada" Type="LLamadasAgenda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Consultores" Member="ConsultoresAgenda">
    <Type Name="ConsultoresAgenda">
      <Column Name="IdConsultor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Identificacion" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TelefonoFijo1" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="TelefonoFijo2" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TelefonoMovil1" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="TelefonoMovil2" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CorreoElectronico" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="Consultores_InstitucionEducativa" Member="InstitucionEducativaAgenda" Storage="_InstitucionEducativa" ThisKey="IdConsultor" OtherKey="IdConsultor" Type="InstitucionEducativaAgenda" />
    </Type>
  </Table>
  <Table Name="dbo.InstitucionEducativa" Member="InstitucionEducativaAgenda">
    <Type Name="InstitucionEducativaAgenda">
      <Column Name="IdIE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdConsultor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodigoDane" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Nombre" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Direccion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Telefono" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Municipio" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Rector" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Email" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="InstitucionEducativa_LLamadas" Member="LLamadasAgenda" Storage="_LLamadas" ThisKey="IdIE" OtherKey="IdIE" Type="LLamadasAgenda" />
      <Association Name="Consultores_InstitucionEducativa" Member="ConsultoresAgenda" Storage="_Consultores" ThisKey="IdConsultor" OtherKey="IdConsultor" Type="ConsultoresAgenda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LLamadas" Member="LLamadasAgenda">
    <Type Name="LLamadasAgenda">
      <Column Name="IdLlamada" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdIE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdOperador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEstadoLLamada" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="LLamadas_Citas" Member="CitasAgenda" Storage="_Citas" ThisKey="IdLlamada" OtherKey="IdLLamada" Type="CitasAgenda" />
      <Association Name="InstitucionEducativa_LLamadas" Member="InstitucionEducativaAgenda" Storage="_InstitucionEducativa" ThisKey="IdIE" OtherKey="IdIE" Type="InstitucionEducativaAgenda" IsForeignKey="true" />
    </Type>
  </Table>
</Database>