<?xml version="1.0" encoding="utf-8"?><Database Name="esm" Class="ESMBDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local)\sqlexpress;Initial Catalog=esm;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="esmConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ActaVisitaEE" Member="ActaVisitaEEs">
    <Type Name="ActaVisitaEE">
      <Column Name="IdActaVisita" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdMedicion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Observaciones" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="ActaVisitaEE_AsociadosActaVisitaEE" Member="AsociadosActaVisitaEEs" ThisKey="IdActaVisita" OtherKey="IdActaVisita" Type="AsociadosActaVisitaEE" />
      <Association Name="Establecimiento_Educativo_ActaVisitaEE" Member="Establecimiento_Educativo" ThisKey="IdEE" OtherKey="IdIE" Type="Establecimiento_Educativo" IsForeignKey="true" />
      <Association Name="Medicione_ActaVisitaEE" Member="Medicione" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Medicione" IsForeignKey="true" />
      <Association Name="Usuario_ActaVisitaEE" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Verbos" Member="Verbos">
    <Type Name="Verbo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Verbo" Member="Verbo1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Verbo_Resultados_Indicadore" Member="Resultados_Indicadores" ThisKey="Id" OtherKey="verbo_id" Type="Resultados_Indicadore" />
      <Association Name="Verbo_Indicadore" Member="Indicadores" ThisKey="Id" OtherKey="verbo_id" Type="Indicadore" />
    </Type>
  </Table>
  <Table Name="dbo.ActaVisitaSE" Member="ActaVisitaSEs">
    <Type Name="ActaVisitaSE">
      <Column Name="IdActaVisita" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdMedicion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdSE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Observaciones" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="ActaVisitaSE_AsociadoActaVisitaSE" Member="AsociadoActaVisitaSEs" ThisKey="IdActaVisita" OtherKey="IdActaVisita" Type="AsociadoActaVisitaSE" />
      <Association Name="Medicione_ActaVisitaSE" Member="Medicione" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Medicione" IsForeignKey="true" />
      <Association Name="Secretaria_Educacion_ActaVisitaSE" Member="Secretaria_Educacion" ThisKey="IdSE" OtherKey="IdSecretaria" Type="Secretaria_Educacion" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Usuario_ActaVisitaSE" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActaVisitaSistematizacion" Member="ActaVisitaSistematizacions">
    <Type Name="ActaVisitaSistematizacion">
      <Column Name="IdActaVisita" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdSE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdEE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdMedicion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Observaciones" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="ActaVisitaSistematizacion_AsociadoActaVisitaSistematizacion" Member="AsociadoActaVisitaSistematizacions" ThisKey="IdActaVisita" OtherKey="IdActaVisita" Type="AsociadoActaVisitaSistematizacion" />
      <Association Name="Establecimiento_Educativo_ActaVisitaSistematizacion" Member="Establecimiento_Educativo" ThisKey="IdEE" OtherKey="IdIE" Type="Establecimiento_Educativo" IsForeignKey="true" />
      <Association Name="Medicione_ActaVisitaSistematizacion" Member="Medicione" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Medicione" IsForeignKey="true" />
      <Association Name="Secretaria_Educacion_ActaVisitaSistematizacion" Member="Secretaria_Educacion" ThisKey="IdSE" OtherKey="IdSecretaria" Type="Secretaria_Educacion" IsForeignKey="true" />
      <Association Name="Usuario_ActaVisitaSistematizacion" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Actividades_Medios" Member="Actividades_Medios">
    <Type Name="Actividades_Medio">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Actividad_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Medios_de_verificacion_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Medios_de_verificacion_Actividades_Medio" Member="Medios_de_verificacion" ThisKey="Medios_de_verificacion_id" OtherKey="Id" Type="Medios_de_verificacion" IsForeignKey="true" />
      <Association Name="Actividade_Actividades_Medio" Member="Actividade" ThisKey="Actividad_id" OtherKey="Id" Type="Actividade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Actividades_Responsables" Member="Actividades_Responsables">
    <Type Name="Actividades_Responsable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Actividad_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Usuario_Actividades_Responsable" Member="Usuario" ThisKey="Usuario_id" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
      <Association Name="Actividade_Actividades_Responsable" Member="Actividade" ThisKey="Actividad_id" OtherKey="Id" Type="Actividade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Actividades_Supuestos" Member="Actividades_Supuestos">
    <Type Name="Actividades_Supuesto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Actividad_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supuesto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Supuesto_Actividades_Supuesto" Member="Supuesto" ThisKey="Supuesto_id" OtherKey="Id" Type="Supuesto" IsForeignKey="true" />
      <Association Name="Actividade_Actividades_Supuesto" Member="Actividade" ThisKey="Actividad_id" OtherKey="Id" Type="Actividade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Actores" Member="Actores">
    <Type Name="Actore">
      <Column Name="IdActor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdRama" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Actor" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Actore_AsociadosActaVisitaEE" Member="AsociadosActaVisitaEEs" ThisKey="IdActor" OtherKey="IdActor" Type="AsociadosActaVisitaEE" />
      <Association Name="Actore_Evaluacion" Member="Evaluacions" ThisKey="IdActor" OtherKey="IdActor" Type="Evaluacion" />
      <Association Name="Rama_Actore" Member="Rama" ThisKey="IdRama" OtherKey="IdRama" Type="Rama" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ambientes" Member="Ambientes">
    <Type Name="Ambiente">
      <Column Name="IdAmbiente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ambiente" Member="Ambiente1" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Ambiente_Proceso" Member="Procesos" ThisKey="IdAmbiente" OtherKey="IdAmbiente" Type="Proceso" />
    </Type>
  </Table>
  <Table Name="dbo.AsignaDocumentos" Member="AsignaDocumentos">
    <Type Name="AsignaDocumento">
      <Column Name="IdDocumentos" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdMedicion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdDocumento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ruta" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Documento_AsignaDocumento" Member="Documento" ThisKey="IdDocumento" OtherKey="IdDocumento" Type="Documento" IsForeignKey="true" />
      <Association Name="Medicione_AsignaDocumento" Member="Medicione" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Medicione" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AsociadoActaVisitaSE" Member="AsociadoActaVisitaSEs">
    <Type Name="AsociadoActaVisitaSE">
      <Column Name="IdAsociado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdActaVisita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CorreoElectronico" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Cargo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="ActaVisitaSE_AsociadoActaVisitaSE" Member="ActaVisitaSE" ThisKey="IdActaVisita" OtherKey="IdActaVisita" Type="ActaVisitaSE" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AsociadoActaVisitaSistematizacion" Member="AsociadoActaVisitaSistematizacions">
    <Type Name="AsociadoActaVisitaSistematizacion">
      <Column Name="IdAsociado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdActaVisita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CorreoElectronico" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Cargo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Institucion" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="ActaVisitaSistematizacion_AsociadoActaVisitaSistematizacion" Member="ActaVisitaSistematizacion" ThisKey="IdActaVisita" OtherKey="IdActaVisita" Type="ActaVisitaSistematizacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AsociadosActaVisitaEE" Member="AsociadosActaVisitaEEs">
    <Type Name="AsociadosActaVisitaEE">
      <Column Name="IdAsociado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdActaVisita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdActor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CorreoElectronico" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Cargo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Grado" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="AreasEnseñansa" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IdNivelEducativo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GradosEnseñansa" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GradoHijos" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Actore_AsociadosActaVisitaEE" Member="Actore" ThisKey="IdActor" OtherKey="IdActor" Type="Actore" IsForeignKey="true" />
      <Association Name="ActaVisitaEE_AsociadosActaVisitaEE" Member="ActaVisitaEE" ThisKey="IdActaVisita" OtherKey="IdActaVisita" Type="ActaVisitaEE" IsForeignKey="true" />
      <Association Name="NivelesEducativo_AsociadosActaVisitaEE" Member="NivelesEducativo" ThisKey="IdNivelEducativo" OtherKey="IdNivelEducativo" Type="NivelesEducativo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AyudaByPregunta" Member="AyudaByPreguntas">
    <Type Name="AyudaByPregunta">
      <Column Name="IdAyuda" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPregunta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PEI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PMI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Manual de Convivencia]" Member="Manual_de_Convivencia" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Planes de Estudio]" Member="Planes_de_Estudio" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DPP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Otros" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Lectura" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Participacion" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Pregunta_AyudaByPregunta" Member="Pregunta" ThisKey="IdPregunta" OtherKey="IdPregunta" Type="Pregunta" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categorias" Member="Categorias">
    <Type Name="Categoria">
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Categoria" Member="Categoria1" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Validacion" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryByComponente" Member="CategoryByComponentes">
    <Type Name="CategoryByComponente">
      <Column Name="IdDesCategoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdComponente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Existencia" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Pertinencia" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Aprobacion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Mejoramiento Continuo]" Member="Mejoramiento_Continuo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Componente_CategoryByComponente" Member="Componente" ThisKey="IdComponente" OtherKey="IdComponente" Type="Componente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Citas" Member="Citas">
    <Type Name="Cita">
      <Column Name="IdCita" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdEstadoCita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaInicio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaFin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Lugar" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IdSE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdEE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Establecimiento_Educativo_Cita" Member="Establecimiento_Educativo" ThisKey="IdEE" OtherKey="IdIE" Type="Establecimiento_Educativo" IsForeignKey="true" />
      <Association Name="EstadoCita_Cita" Member="EstadoCita" ThisKey="IdEstadoCita" OtherKey="IdEstadoCita" Type="EstadoCita" IsForeignKey="true" />
      <Association Name="Secretaria_Educacion_Cita" Member="Secretaria_Educacion" ThisKey="IdSE" OtherKey="IdSecretaria" Type="Secretaria_Educacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Componentes" Member="Componentes">
    <Type Name="Componente">
      <Column Name="IdComponente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdProceso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Componente" Member="Componente1" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Componente_CategoryByComponente" Member="CategoryByComponentes" ThisKey="IdComponente" OtherKey="IdComponente" Type="CategoryByComponente" />
      <Association Name="Componente_Pregunta" Member="Preguntas" ThisKey="IdComponente" OtherKey="IdComponente" Type="Pregunta" />
      <Association Name="Proceso_Componente" Member="Proceso" ThisKey="IdProceso" OtherKey="IdProceso" Type="Proceso" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.ConslAmbiente" Member="ConslAmbientes">
    <Type Name="ConslAmbiente">
      <Column Name="IdConslAmbiente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdConsolidado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdAmbiente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(15,3)" CanBeNull="true" />
      <Association Name="Consolidacion_ConslAmbiente" Member="Consolidacion" ThisKey="IdConsolidado" OtherKey="IdConsolidacion" Type="Consolidacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ConslComponente" Member="ConslComponentes">
    <Type Name="ConslComponente">
      <Column Name="IdConslComponente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdConsolidado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdComponente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(15,3) NOT NULL" CanBeNull="false" />
      <Association Name="Consolidacion_ConslComponente" Member="Consolidacion" ThisKey="IdConsolidado" OtherKey="IdConsolidacion" Type="Consolidacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ConslPregunta" Member="ConslPreguntas">
    <Type Name="ConslPregunta">
      <Column Name="IdConslPregunta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdConsolidado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPregunta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Valor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NoAplica" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Consolidacion_ConslPregunta" Member="Consolidacion" ThisKey="IdConsolidado" OtherKey="IdConsolidacion" Type="Consolidacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ConslProceso" Member="ConslProcesos">
    <Type Name="ConslProceso">
      <Column Name="IdConslProceso" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdConsolidado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdProceso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(15,3)" CanBeNull="true" />
      <Association Name="Consolidacion_ConslProceso" Member="Consolidacion" ThisKey="IdConsolidado" OtherKey="IdConsolidacion" Type="Consolidacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Consolidacion" Member="Consolidacions">
    <Type Name="Consolidacion">
      <Column Name="IdConsolidacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdMedicion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdIE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Consolidacion_ConslAmbiente" Member="ConslAmbientes" ThisKey="IdConsolidacion" OtherKey="IdConsolidado" Type="ConslAmbiente" />
      <Association Name="Consolidacion_ConslComponente" Member="ConslComponentes" ThisKey="IdConsolidacion" OtherKey="IdConsolidado" Type="ConslComponente" />
      <Association Name="Consolidacion_ConslPregunta" Member="ConslPreguntas" ThisKey="IdConsolidacion" OtherKey="IdConsolidado" Type="ConslPregunta" />
      <Association Name="Consolidacion_ConslProceso" Member="ConslProcesos" ThisKey="IdConsolidacion" OtherKey="IdConsolidado" Type="ConslProceso" />
      <Association Name="Establecimiento_Educativo_Consolidacion" Member="Establecimiento_Educativo" ThisKey="IdIE" OtherKey="IdIE" Type="Establecimiento_Educativo" IsForeignKey="true" />
      <Association Name="Medicione_Consolidacion" Member="Medicione" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Medicione" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Consultores" Member="Consultores">
    <Type Name="Consultore">
      <Column Name="IdConsultor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Identificacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TelefonoFijo1" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TelefonoFijo2" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TelefonoMovil1" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TelefonoMovil2" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CorreoElectronico" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="Consultore_Secretaria_Educacion" Member="Secretaria_Educacions" ThisKey="IdConsultor" OtherKey="IdConsultor" Type="Secretaria_Educacion" />
      <Association Name="Consultore_Usuario" Member="Usuarios" ThisKey="IdConsultor" OtherKey="IdConsultor" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Documentos" Member="Documentos">
    <Type Name="Documento">
      <Column Name="IdDocumento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Documento" Member="Documento1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Documento_AsignaDocumento" Member="AsignaDocumentos" ThisKey="IdDocumento" OtherKey="IdDocumento" Type="AsignaDocumento" />
    </Type>
  </Table>
  <Table Name="dbo.[Establecimiento Educativo]" Member="Establecimiento_Educativos">
    <Type Name="Establecimiento_Educativo">
      <Column Name="IdIE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodigoDane" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Nombre" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Direccion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Telefono" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Municipio" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Rector" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Email" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IdSE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sistematizacion" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Establecimiento_Educativo_ActaVisitaEE" Member="ActaVisitaEEs" ThisKey="IdIE" OtherKey="IdEE" Type="ActaVisitaEE" />
      <Association Name="Establecimiento_Educativo_ActaVisitaSistematizacion" Member="ActaVisitaSistematizacions" ThisKey="IdIE" OtherKey="IdEE" Type="ActaVisitaSistematizacion" />
      <Association Name="Establecimiento_Educativo_Cita" Member="Citas" ThisKey="IdIE" OtherKey="IdEE" Type="Cita" />
      <Association Name="Establecimiento_Educativo_Consolidacion" Member="Consolidacions" ThisKey="IdIE" OtherKey="IdIE" Type="Consolidacion" />
      <Association Name="Establecimiento_Educativo_Evaluacion" Member="Evaluacions" ThisKey="IdIE" OtherKey="IdIE" Type="Evaluacion" />
      <Association Name="Establecimiento_Educativo_LecturaContextoEE" Member="LecturaContextoEEs" ThisKey="IdIE" OtherKey="IdIE" Type="LecturaContextoEE" />
      <Association Name="Establecimiento_Educativo_LLamada" Member="LLamadas" ThisKey="IdIE" OtherKey="IdEE" Type="LLamada" />
      <Association Name="Establecimiento_Educativo_Sistematizacion" Member="Sistematizacions" ThisKey="IdIE" OtherKey="IdEE" Type="Sistematizacion" />
      <Association Name="Secretaria_Educacion_Establecimiento_Educativo" Member="Secretaria_Educacion" ThisKey="IdSE" OtherKey="IdSecretaria" Type="Secretaria_Educacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EstadoCita" Member="EstadoCitas">
    <Type Name="EstadoCita">
      <Column Name="IdEstadoCita" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EstadoCita" Member="EstadoCita1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="EstadoCita_Cita" Member="Citas" ThisKey="IdEstadoCita" OtherKey="IdEstadoCita" Type="Cita" />
    </Type>
  </Table>
  <Table Name="dbo.EstadoEvaluacion" Member="EstadoEvaluacions">
    <Type Name="EstadoEvaluacion">
      <Column Name="IdEstado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="EstadoEvaluacion_Evaluacion" Member="Evaluacions" ThisKey="IdEstado" OtherKey="IdEstado" Type="Evaluacion" />
    </Type>
  </Table>
  <Table Name="dbo.EstadoLLamadas" Member="EstadoLLamadas">
    <Type Name="EstadoLLamada">
      <Column Name="IdEstadoLLamada" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EstadoLLamada" Member="EstadoLLamada1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="EstadoLLamada_LLamada" Member="LLamadas" ThisKey="IdEstadoLLamada" OtherKey="IdEstadoLLamada" Type="LLamada" />
    </Type>
  </Table>
  <Table Name="dbo.Evaluacion" Member="Evaluacions">
    <Type Name="Evaluacion">
      <Column Name="IdEvaluacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdIE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdActor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEstado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdMedicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Evaluacion_ResultadosByEvaluacion" Member="ResultadosByEvaluacions" ThisKey="IdEvaluacion" OtherKey="IdEvaluacion" Type="ResultadosByEvaluacion" />
      <Association Name="Actore_Evaluacion" Member="Actore" ThisKey="IdActor" OtherKey="IdActor" Type="Actore" IsForeignKey="true" />
      <Association Name="EstadoEvaluacion_Evaluacion" Member="EstadoEvaluacion" ThisKey="IdEstado" OtherKey="IdEstado" Type="EstadoEvaluacion" IsForeignKey="true" />
      <Association Name="Establecimiento_Educativo_Evaluacion" Member="Establecimiento_Educativo" ThisKey="IdIE" OtherKey="IdIE" Type="Establecimiento_Educativo" IsForeignKey="true" />
      <Association Name="Medicione_Evaluacion" Member="Medicione" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Medicione" IsForeignKey="true" />
      <Association Name="Secretaria_Educacion_Evaluacion" Member="Secretaria_Educacion" ThisKey="IdSE" OtherKey="IdSecretaria" Type="Secretaria_Educacion" IsForeignKey="true" />
      <Association Name="Usuario_Evaluacion" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Indicadores_Responsables" Member="Indicadores_Responsables">
    <Type Name="Indicadores_Responsable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Indicador_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Usuario_Indicadores_Responsable" Member="Usuario" ThisKey="Usuario_id" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
      <Association Name="Indicadore_Indicadores_Responsable" Member="Indicadore" ThisKey="Indicador_id" OtherKey="Id" Type="Indicadore" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LecturaContextoEE" Member="LecturaContextoEEs">
    <Type Name="LecturaContextoEE">
      <Column Name="IdLecturaContextoEE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdIE" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdMedicion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NumeroSedes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="f11" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="f12" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="f13" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="f14" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="f15" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C_1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C_2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C_3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C_4" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C_5" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_1_2bUrbana]" Member="_1_2bUrbana" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_1_2bRural]" Member="_1_2bRural" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_2_1]" Member="_2_1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_E1]" Member="_2_2_E1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_E2]" Member="_2_2_E2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_E3]" Member="_2_2_E3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_E4]" Member="_2_2_E4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_E5]" Member="_2_2_E5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_E6]" Member="_2_2_E6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_3_S1]" Member="_2_3_S1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_3_S2]" Member="_2_3_S2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_3_S3]" Member="_2_3_S3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_3_S4]" Member="_2_3_S4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_3_NoSabe]" Member="_2_3_NoSabe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_3_NoTiene]" Member="_2_3_NoTiene" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_4_Si]" Member="_2_4_Si" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_2_4_No]" Member="_2_4_No" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_2_5_1]" Member="_2_5_1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_5_2]" Member="_2_5_2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_5_3]" Member="_2_5_3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_3_1]" Member="_3_1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_2]" Member="_3_2" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_3]" Member="_3_3" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_4_Si]" Member="_3_4_Si" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_3_4_No]" Member="_3_4_No" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_3_4_1]" Member="_3_4_1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_5_Si]" Member="_3_5_Si" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_3_5_No]" Member="_3_5_No" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_3_5_1]" Member="_3_5_1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_5_2]" Member="_3_5_2" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_5_3]" Member="_3_5_3" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_5_4]" Member="_3_5_4" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_5_5]" Member="_3_5_5" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_5_6]" Member="_3_5_6" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_5_7]" Member="_3_5_7" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_6]" Member="_3_6" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_7]" Member="_3_7" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_8_Si]" Member="_3_8_Si" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_3_8_No]" Member="_3_8_No" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_3_8_1]" Member="_3_8_1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_9_Si]" Member="_3_9_Si" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_3_9_No]" Member="_3_9_No" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_3_9_1]" Member="_3_9_1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_4_1_Si]" Member="_4_1_Si" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_4_1_No]" Member="_4_1_No" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_4_1_Algunas]" Member="_4_1_Algunas" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_4_2]" Member="_4_2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_4_3_Si]" Member="_4_3_Si" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_4_3_No]" Member="_4_3_No" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_4_3_1]" Member="_4_3_1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_5_1_Si]" Member="_5_1_Si" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_5_1_No]" Member="_5_1_No" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_5_1_1]" Member="_5_1_1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Observaciones" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Establecimiento_Educativo_LecturaContextoEE" Member="Establecimiento_Educativo" ThisKey="IdIE" OtherKey="IdIE" Type="Establecimiento_Educativo" IsForeignKey="true" />
      <Association Name="Medicione_LecturaContextoEE" Member="Medicione" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Medicione" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LecturaContextoSE" Member="LecturaContextoSEs">
    <Type Name="LecturaContextoSE">
      <Column Name="IdLecturaContexto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdMedicion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdSecretaria" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[_2_1_]" Member="_2_1_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_2_2_]" Member="_2_2_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_2_2_1_]" Member="_2_2_1_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_2_2_2_]" Member="_2_2_2_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_2_2_4_]" Member="_2_2_4_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_2_2_5_]" Member="_2_2_5_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_2_2_3_EE_]" Member="_2_2_3_EE_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_2_2_3_EE_Cant]" Member="_2_2_3_EE_Cant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_3_EST_]" Member="_2_2_3_EST_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_2_2_3_EST_Cant]" Member="_2_2_3_EST_Cant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_3_EDU]" Member="_2_2_3_EDU" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_2_2_3_EDU_Cant]" Member="_2_2_3_EDU_Cant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_3_DIR_]" Member="_2_2_3_DIR_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_2_2_3_DIR_Cant]" Member="_2_2_3_DIR_Cant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_3_PAD_]" Member="_2_2_3_PAD_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_2_2_3_PAD_Cant]" Member="_2_2_3_PAD_Cant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_3_OTR_1]" Member="_2_2_3_OTR_1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_2_2_3_OTR_1_Cant]" Member="_2_2_3_OTR_1_Cant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_3_OTR_2]" Member="_2_2_3_OTR_2" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_2_2_3_OTR_2_Cant]" Member="_2_2_3_OTR_2_Cant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_3_OTR_3_]" Member="_2_2_3_OTR_3_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_2_2_3_OTR_3_Cant]" Member="_2_2_3_OTR_3_Cant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_3_OTR_4_]" Member="_2_2_3_OTR_4_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_2_2_3_OTR_4_Cant]" Member="_2_2_3_OTR_4_Cant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_2_3_OTR_5_]" Member="_2_2_3_OTR_5_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_2_2_3_OTR_5_Cant]" Member="_2_2_3_OTR_5_Cant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_2_3_]" Member="_2_3_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_2_3_1_]" Member="_2_3_1_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_1_]" Member="_3_1_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_2_]" Member="_3_2_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_3_]" Member="_3_3_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_4_]" Member="_3_4_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_5_]" Member="_3_5_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_3_6_]" Member="_3_6_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_4_1_]" Member="_4_1_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_4_1_1_]" Member="_4_1_1_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_5_1_RADD_]" Member="_5_1_RADD_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_5_1_RADM]" Member="_5_1_RADM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_5_1_PREND]" Member="_5_1_PREND" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_5_1_PRENM]" Member="_5_1_PRENM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_5_1_TELD]" Member="_5_1_TELD" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_5_1_TELM]" Member="_5_1_TELM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_5_1_INT]" Member="_5_1_INT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_5_1_INTM]" Member="_5_1_INTM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_5_2_]" Member="_5_2_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_1_1_8_]" Member="_1_1_8_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_1_1_9_]" Member="_1_1_9_" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Observaciones" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Medicione_LecturaContextoSE" Member="Medicione" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Medicione" IsForeignKey="true" />
      <Association Name="Secretaria_Educacion_LecturaContextoSE" Member="Secretaria_Educacion" ThisKey="IdSecretaria" OtherKey="IdSecretaria" Type="Secretaria_Educacion" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LLamadas" Member="LLamadas">
    <Type Name="LLamada">
      <Column Name="IdLlamada" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdSE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdEE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEstadoLLamada" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Establecimiento_Educativo_LLamada" Member="Establecimiento_Educativo" ThisKey="IdEE" OtherKey="IdIE" Type="Establecimiento_Educativo" IsForeignKey="true" />
      <Association Name="EstadoLLamada_LLamada" Member="EstadoLLamada" ThisKey="IdEstadoLLamada" OtherKey="IdEstadoLLamada" Type="EstadoLLamada" IsForeignKey="true" />
      <Association Name="Secretaria_Educacion_LLamada" Member="Secretaria_Educacion" ThisKey="IdSE" OtherKey="IdSecretaria" Type="Secretaria_Educacion" IsForeignKey="true" />
      <Association Name="Usuario_LLamada" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mediciones" Member="Mediciones">
    <Type Name="Medicione">
      <Column Name="IdMedicion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaMedicion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Medicione_ActaVisitaEE" Member="ActaVisitaEEs" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="ActaVisitaEE" />
      <Association Name="Medicione_ActaVisitaSE" Member="ActaVisitaSEs" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="ActaVisitaSE" />
      <Association Name="Medicione_ActaVisitaSistematizacion" Member="ActaVisitaSistematizacions" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="ActaVisitaSistematizacion" />
      <Association Name="Medicione_AsignaDocumento" Member="AsignaDocumentos" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="AsignaDocumento" />
      <Association Name="Medicione_Consolidacion" Member="Consolidacions" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Consolidacion" />
      <Association Name="Medicione_Evaluacion" Member="Evaluacions" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Evaluacion" />
      <Association Name="Medicione_LecturaContextoEE" Member="LecturaContextoEEs" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="LecturaContextoEE" />
      <Association Name="Medicione_LecturaContextoSE" Member="LecturaContextoSEs" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="LecturaContextoSE" />
      <Association Name="Medicione_Sistematizacion" Member="Sistematizacions" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Sistematizacion" />
      <Association Name="Medicione_SistematizacionSE" Member="SistematizacionSEs" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="SistematizacionSE" />
    </Type>
  </Table>
  <Table Name="dbo.Medios_de_verificacion" Member="Medios_de_verificacions">
    <Type Name="Medios_de_verificacion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Medio_de_verificacion" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Medios_de_verificacion_Actividades_Medio" Member="Actividades_Medios" ThisKey="Id" OtherKey="Medios_de_verificacion_id" Type="Actividades_Medio" />
      <Association Name="Medios_de_verificacion_Proyectos_Medio" Member="Proyectos_Medios" ThisKey="Id" OtherKey="Medios_de_verificacion_id" Type="Proyectos_Medio" />
      <Association Name="Medios_de_verificacion_Resultados_Medio" Member="Resultados_Medios" ThisKey="Id" OtherKey="Medios_de_verificacion_id" Type="Resultados_Medio" />
      <Association Name="Medios_de_verificacion_Subprocesos_Medios_Verificacion" Member="Subprocesos_Medios_Verificacions" ThisKey="Id" OtherKey="Medio_Verificacion_id" Type="Subprocesos_Medios_Verificacion" />
    </Type>
  </Table>
  <Table Name="dbo.NivelesEducativos" Member="NivelesEducativos">
    <Type Name="NivelesEducativo">
      <Column Name="IdNivelEducativo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NivelEducativo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="NivelesEducativo_AsociadosActaVisitaEE" Member="AsociadosActaVisitaEEs" ThisKey="IdNivelEducativo" OtherKey="IdNivelEducativo" Type="AsociadosActaVisitaEE" />
    </Type>
  </Table>
  <Table Name="dbo.Operadores" Member="Operadores">
    <Type Name="Operadore">
      <Column Name="IdOperador" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Identificacion" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CorreoElectonico" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="Operadore_Usuario" Member="Usuarios" ThisKey="IdOperador" OtherKey="IdOperador" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Preguntas" Member="Preguntas">
    <Type Name="Pregunta">
      <Column Name="IdPregunta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdComponente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pregunta" Member="Pregunta1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Padres" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Docente" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Profesional" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estudiante" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Directivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Sesiones" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdPrivilegiado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdOrden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Etiqueta" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Ocultar" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Pregunta_AyudaByPregunta" Member="AyudaByPreguntas" ThisKey="IdPregunta" OtherKey="IdPregunta" Type="AyudaByPregunta" />
      <Association Name="Pregunta_Resultado" Member="Resultados" ThisKey="IdPregunta" OtherKey="IdPregunta" Type="Resultado" />
      <Association Name="Componente_Pregunta" Member="Componente" ThisKey="IdComponente" OtherKey="IdComponente" Type="Componente" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Privilegiado_Pregunta" Member="Privilegiado" ThisKey="IdPrivilegiado" OtherKey="IdPrivilegiado" Type="Privilegiado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Privilegiados" Member="Privilegiados">
    <Type Name="Privilegiado">
      <Column Name="IdPrivilegiado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Privilegiado" Member="Privilegiado1" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Privilegiado_Pregunta" Member="Preguntas" ThisKey="IdPrivilegiado" OtherKey="IdPrivilegiado" Type="Pregunta" />
    </Type>
  </Table>
  <Table Name="dbo.Procesos" Member="Procesos">
    <Type Name="Proceso">
      <Column Name="IdProceso" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdAmbiente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Proceso" Member="Proceso1" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Proceso_Componente" Member="Componentes" ThisKey="IdProceso" OtherKey="IdProceso" Type="Componente" />
      <Association Name="Ambiente_Proceso" Member="Ambiente" ThisKey="IdAmbiente" OtherKey="IdAmbiente" Type="Ambiente" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Proyectos" Member="Proyectos">
    <Type Name="Proyecto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Proyecto" Member="Proyecto1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Problema" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Finalidad" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Proposito" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Fecha_Creacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Indicador" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Presupuesto" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Proyecto_Proyectos_Medio" Member="Proyectos_Medios" ThisKey="Id" OtherKey="Proyecto_id" Type="Proyectos_Medio" />
      <Association Name="Proyecto_Proyectos_Supuesto" Member="Proyectos_Supuestos" ThisKey="Id" OtherKey="Proyecto_supuesto_id" Type="Proyectos_Supuesto" />
      <Association Name="Proyecto_Fuentes_Financiacion" Member="Fuentes_Financiacions" ThisKey="Id" OtherKey="proyecto_id" Type="Fuentes_Financiacion" />
      <Association Name="Proyecto_Matriz_Actore" Member="Matriz_Actores" ThisKey="Id" OtherKey="proyecto_id" Type="Matriz_Actore" />
      <Association Name="Proyecto_Documentos_Proyecto" Member="Documentos_Proyectos" ThisKey="Id" OtherKey="proyectoid" Type="Documentos_Proyecto" />
      <Association Name="Proyecto_Causas_Efecto" Member="Causas_Efectos" ThisKey="Id" OtherKey="Proyecto_id" Type="Causas_Efecto" />
      <Association Name="Proyecto_Registro_Proyecto" Member="Registro_Proyectos" ThisKey="Id" OtherKey="proyecto_id" Type="Registro_Proyecto" />
    </Type>
  </Table>
  <Table Name="dbo.Proyectos_Medios" Member="Proyectos_Medios">
    <Type Name="Proyectos_Medio">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Proyecto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Medios_de_verificacion_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Proyecto_Proyectos_Medio" Member="Proyecto" ThisKey="Proyecto_id" OtherKey="Id" Type="Proyecto" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Medios_de_verificacion_Proyectos_Medio" Member="Medios_de_verificacion" ThisKey="Medios_de_verificacion_id" OtherKey="Id" Type="Medios_de_verificacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Proyectos_Supuestos" Member="Proyectos_Supuestos">
    <Type Name="Proyectos_Supuesto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Proyecto_supuesto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supuesto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Proyecto_Proyectos_Supuesto" Member="Proyecto" ThisKey="Proyecto_supuesto_id" OtherKey="Id" Type="Proyecto" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Supuesto_Proyectos_Supuesto" Member="Supuesto" ThisKey="Supuesto_id" OtherKey="Id" Type="Supuesto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rama" Member="Ramas">
    <Type Name="Rama">
      <Column Name="IdRama" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Evaluado" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Rama_Actore" Member="Actores" ThisKey="IdRama" OtherKey="IdRama" Type="Actore" />
    </Type>
  </Table>
  <Table Name="dbo.Responsables" Member="Responsables">
    <Type Name="Responsable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usuario_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Responsable" Member="Responsable1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cargo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Responsables_Resultados" Member="Responsables_Resultados">
    <Type Name="Responsables_Resultado">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Actividad_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Responsable_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Actividade_Responsables_Resultado" Member="Actividade" ThisKey="Actividad_id" OtherKey="Id" Type="Actividade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Resultados" Member="Resultados">
    <Type Name="Resultado">
      <Column Name="IdResultados" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPregunta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Valor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Pendiente" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Sesiones" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Resultado_ResultadosByEvaluacion" Member="ResultadosByEvaluacions" ThisKey="IdResultados" OtherKey="IdResultado" Type="ResultadosByEvaluacion" />
      <Association Name="Pregunta_Resultado" Member="Pregunta" ThisKey="IdPregunta" OtherKey="IdPregunta" Type="Pregunta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Resultados_Indicadores" Member="Resultados_Indicadores">
    <Type Name="Resultados_Indicadore">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Resultado_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Resultado_indicador" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="unidad" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="verbo_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="upsize_ts" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Association Name="Verbo_Resultados_Indicadore" Member="Verbo" ThisKey="verbo_id" OtherKey="Id" Type="Verbo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Resultados_Medios" Member="Resultados_Medios">
    <Type Name="Resultados_Medio">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Resultado_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Medios_de_verificacion_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Medios_de_verificacion_Resultados_Medio" Member="Medios_de_verificacion" ThisKey="Medios_de_verificacion_id" OtherKey="Id" Type="Medios_de_verificacion" IsForeignKey="true" />
      <Association Name="Resultados_Proyecto_Resultados_Medio" Member="Resultados_Proyecto" ThisKey="Resultado_id" OtherKey="Id" Type="Resultados_Proyecto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Resultados_Proyectos" Member="Resultados_Proyectos">
    <Type Name="Resultados_Proyecto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subproceso_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Resultado" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Indicador" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Association Name="Resultados_Proyecto_Resultados_Medio" Member="Resultados_Medios" ThisKey="Id" OtherKey="Resultado_id" Type="Resultados_Medio" />
      <Association Name="Resultados_Proyecto_Resultados_Supuesto" Member="Resultados_Supuestos" ThisKey="Id" OtherKey="Resultado_id" Type="Resultados_Supuesto" />
    </Type>
  </Table>
  <Table Name="dbo.Resultados_Supuestos" Member="Resultados_Supuestos">
    <Type Name="Resultados_Supuesto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Resultado_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supuesto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Resultados_Proyecto_Resultados_Supuesto" Member="Resultados_Proyecto" ThisKey="Resultado_id" OtherKey="Id" Type="Resultados_Proyecto" IsForeignKey="true" />
      <Association Name="Supuesto_Resultados_Supuesto" Member="Supuesto" ThisKey="Supuesto_id" OtherKey="Id" Type="Supuesto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ResultadosByEvaluacion" Member="ResultadosByEvaluacions">
    <Type Name="ResultadosByEvaluacion">
      <Column Name="IdResultadosbyPregunta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdResultado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEvaluacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Evaluacion_ResultadosByEvaluacion" Member="Evaluacion" ThisKey="IdEvaluacion" OtherKey="IdEvaluacion" Type="Evaluacion" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Resultado_ResultadosByEvaluacion" Member="Resultado" ThisKey="IdResultado" OtherKey="IdResultados" Type="Resultado" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="IdRol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Rol" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Association Name="Role_Usuario" Member="Usuarios" ThisKey="IdRol" OtherKey="IdRol" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.[Secretaria Educacion]" Member="Secretaria_Educacions">
    <Type Name="Secretaria_Educacion">
      <Column Name="IdSecretaria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="DepMun" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="TelefonoMovil" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Departamental" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Municipal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Nombre Secretario Educacion]" Member="Nombre_Secretario_Educacion" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[Telefonos Secretario Educacion]" Member="Telefonos_Secretario_Educacion" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="[Correo Electronico]" Member="Correo_Electronico" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IdConsultor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sistematizacion" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Secretaria_Educacion_ActaVisitaSE" Member="ActaVisitaSEs" ThisKey="IdSecretaria" OtherKey="IdSE" Type="ActaVisitaSE" />
      <Association Name="Secretaria_Educacion_ActaVisitaSistematizacion" Member="ActaVisitaSistematizacions" ThisKey="IdSecretaria" OtherKey="IdSE" Type="ActaVisitaSistematizacion" />
      <Association Name="Secretaria_Educacion_Cita" Member="Citas" ThisKey="IdSecretaria" OtherKey="IdSE" Type="Cita" />
      <Association Name="Secretaria_Educacion_Establecimiento_Educativo" Member="Establecimiento_Educativos" ThisKey="IdSecretaria" OtherKey="IdSE" Type="Establecimiento_Educativo" />
      <Association Name="Secretaria_Educacion_Evaluacion" Member="Evaluacions" ThisKey="IdSecretaria" OtherKey="IdSE" Type="Evaluacion" />
      <Association Name="Secretaria_Educacion_LecturaContextoSE" Member="LecturaContextoSEs" ThisKey="IdSecretaria" OtherKey="IdSecretaria" Type="LecturaContextoSE" />
      <Association Name="Secretaria_Educacion_LLamada" Member="LLamadas" ThisKey="IdSecretaria" OtherKey="IdSE" Type="LLamada" />
      <Association Name="Secretaria_Educacion_SistematizacionSE" Member="SistematizacionSEs" ThisKey="IdSecretaria" OtherKey="IdSE" Type="SistematizacionSE" />
      <Association Name="Consultore_Secretaria_Educacion" Member="Consultore" ThisKey="IdConsultor" OtherKey="IdConsultor" Type="Consultore" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sistematizacion" Member="Sistematizacions">
    <Type Name="Sistematizacion">
      <Column Name="IdSistematizacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdMedicion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdEE" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="P1" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="P2" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="P3" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="P4" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="P5" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="P6" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Association Name="Establecimiento_Educativo_Sistematizacion" Member="Establecimiento_Educativo" ThisKey="IdEE" OtherKey="IdIE" Type="Establecimiento_Educativo" IsForeignKey="true" />
      <Association Name="Medicione_Sistematizacion" Member="Medicione" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Medicione" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SistematizacionSE" Member="SistematizacionSEs">
    <Type Name="SistematizacionSE">
      <Column Name="IdSistematizacion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdMedicion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdSE" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="P1" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="P2" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="P3" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="P4" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="P5" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="P6" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Association Name="Medicione_SistematizacionSE" Member="Medicione" ThisKey="IdMedicion" OtherKey="IdMedicion" Type="Medicione" IsForeignKey="true" />
      <Association Name="Secretaria_Educacion_SistematizacionSE" Member="Secretaria_Educacion" ThisKey="IdSE" OtherKey="IdSecretaria" Type="Secretaria_Educacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subprocesos_Medios_Verificacion" Member="Subprocesos_Medios_Verificacions">
    <Type Name="Subprocesos_Medios_Verificacion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subproceso_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Medio_Verificacion_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Medios_de_verificacion_Subprocesos_Medios_Verificacion" Member="Medios_de_verificacion" ThisKey="Medio_Verificacion_id" OtherKey="Id" Type="Medios_de_verificacion" IsForeignKey="true" />
      <Association Name="Subproceso_Subprocesos_Medios_Verificacion" Member="Subproceso" ThisKey="Subproceso_id" OtherKey="Id" Type="Subproceso" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subprocesos_Supuestos" Member="Subprocesos_Supuestos">
    <Type Name="Subprocesos_Supuesto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subproceso_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supuestos_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Supuesto_Subprocesos_Supuesto" Member="Supuesto" ThisKey="Supuestos_id" OtherKey="Id" Type="Supuesto" IsForeignKey="true" />
      <Association Name="Subproceso_Subprocesos_Supuesto" Member="Subproceso" ThisKey="Subproceso_id" OtherKey="Id" Type="Subproceso" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Supuestos" Member="Supuestos">
    <Type Name="Supuesto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="supuesto" Member="supuesto1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Supuesto_Actividades_Supuesto" Member="Actividades_Supuestos" ThisKey="Id" OtherKey="Supuesto_id" Type="Actividades_Supuesto" />
      <Association Name="Supuesto_Proyectos_Supuesto" Member="Proyectos_Supuestos" ThisKey="Id" OtherKey="Supuesto_id" Type="Proyectos_Supuesto" />
      <Association Name="Supuesto_Resultados_Supuesto" Member="Resultados_Supuestos" ThisKey="Id" OtherKey="Supuesto_id" Type="Resultados_Supuesto" />
      <Association Name="Supuesto_Subprocesos_Supuesto" Member="Subprocesos_Supuestos" ThisKey="Id" OtherKey="Supuestos_id" Type="Subprocesos_Supuesto" />
    </Type>
  </Table>
  <Table Name="dbo.Unidades" Member="Unidades">
    <Type Name="Unidade">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Unidad" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Unidade_Indicadore" Member="Indicadores" ThisKey="Id" OtherKey="unidad_id" Type="Indicadore" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdConsultor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Member="Usuario1" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Contrasena" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="IdOperador" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_ActaVisitaEE" Member="ActaVisitaEEs" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="ActaVisitaEE" />
      <Association Name="Usuario_ActaVisitaSE" Member="ActaVisitaSEs" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="ActaVisitaSE" />
      <Association Name="Usuario_ActaVisitaSistematizacion" Member="ActaVisitaSistematizacions" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="ActaVisitaSistematizacion" />
      <Association Name="Usuario_Actividades_Responsable" Member="Actividades_Responsables" ThisKey="IdUsuario" OtherKey="Usuario_id" Type="Actividades_Responsable" />
      <Association Name="Usuario_Evaluacion" Member="Evaluacions" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Evaluacion" />
      <Association Name="Usuario_Indicadores_Responsable" Member="Indicadores_Responsables" ThisKey="IdUsuario" OtherKey="Usuario_id" Type="Indicadores_Responsable" />
      <Association Name="Usuario_LLamada" Member="LLamadas" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="LLamada" />
      <Association Name="Consultore_Usuario" Member="Consultore" ThisKey="IdConsultor" OtherKey="IdConsultor" Type="Consultore" IsForeignKey="true" />
      <Association Name="Operadore_Usuario" Member="Operadore" ThisKey="IdOperador" OtherKey="IdOperador" Type="Operadore" IsForeignKey="true" />
      <Association Name="Role_Usuario" Member="Role" ThisKey="IdRol" OtherKey="IdRol" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.actividad_indicador_mc" Member="actividad_indicador_mcs">
    <Type Name="actividad_indicador_mc">
      <Column Name="Indicador" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SSP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Fecha_Creacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecha_indicador_inicial" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecha_indicador_final" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Actividad_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.gantt" Member="gantts">
    <Type Name="gantt">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Actividad" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Indicador" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[fecha inicial]" Member="fecha_inicial" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="[fecha final]" Member="fecha_final" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Resultado_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Proyecto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report_Full_Actividades" Member="Report_Full_Actividades">
    <Type Name="Report_Full_Actividade">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Actividad" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Presupuesto" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="causa_efecto_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="proyecto_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Medios de Verificacion]" Member="Medios_de_Verificacion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Indicadores" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Resultado" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report_Macro_Logico" Member="Report_Macro_Logicos">
    <Type Name="Report_Macro_Logico">
      <Column Name="Proyecto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Resultado" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Indicador_Resultado" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="[Medios de Verificacion]" Member="Medios_de_Verificacion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Supuestos" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report_Marco_Logico_Propositos" Member="Report_Marco_Logico_Propositos">
    <Type Name="Report_Marco_Logico_Proposito">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Proposito" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Indicador" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="[Medios de Verificacion]" Member="Medios_de_Verificacion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Supuestos" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Indicadores_Metas" Member="Indicadores_Metas">
    <Type Name="Indicadores_Meta">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Indicador_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Meta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha_Meta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Ejecutado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Indicadore_Indicadores_Meta" Member="Indicadore" ThisKey="Indicador_id" OtherKey="Id" Type="Indicadore" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.actividades_presupuesto" Member="actividades_presupuestos">
    <Type Name="actividades_presupuesto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="actividad_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="meta" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ejecutado" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Actividade_actividades_presupuesto" Member="Actividade" ThisKey="actividad_id" OtherKey="Id" Type="Actividade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fuentes_Financiacion" Member="Fuentes_Financiacions">
    <Type Name="Fuentes_Financiacion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tipo_Entidad" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Entidad" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Tipo_Recurso" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="proyecto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Proyecto_Fuentes_Financiacion" Member="Proyecto" ThisKey="proyecto_id" OtherKey="Id" Type="Proyecto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Matriz_Actores" Member="Matriz_Actores">
    <Type Name="Matriz_Actore">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Grupos" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Interes" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Problema_Percibido" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Recursos_Mandatos" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="proyecto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Proyecto_Matriz_Actore" Member="Proyecto" ThisKey="proyecto_id" OtherKey="Id" Type="Proyecto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subprocesos" Member="Subprocesos">
    <Type Name="Subproceso">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Proceso_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subproceso" Member="Subproceso1" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Indicador" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Medios" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Supuestos" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Subproceso_Subprocesos_Medios_Verificacion" Member="Subprocesos_Medios_Verificacions" ThisKey="Id" OtherKey="Subproceso_id" Type="Subprocesos_Medios_Verificacion" />
      <Association Name="Subproceso_Subprocesos_Supuesto" Member="Subprocesos_Supuestos" ThisKey="Id" OtherKey="Subproceso_id" Type="Subprocesos_Supuesto" />
      <Association Name="Subproceso_Actividade" Member="Actividades" ThisKey="Id" OtherKey="Subproceso_id" Type="Actividade" />
      <Association Name="Causas_Efecto_Subproceso" Member="Causas_Efecto" ThisKey="Proceso_id" OtherKey="Id" Type="Causas_Efecto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Actividades" Member="Actividades">
    <Type Name="Actividade">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subproceso_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Actividad" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Presupuesto" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Actividade_Actividades_Medio" Member="Actividades_Medios" ThisKey="Id" OtherKey="Actividad_id" Type="Actividades_Medio" />
      <Association Name="Actividade_Actividades_Responsable" Member="Actividades_Responsables" ThisKey="Id" OtherKey="Actividad_id" Type="Actividades_Responsable" />
      <Association Name="Actividade_Actividades_Supuesto" Member="Actividades_Supuestos" ThisKey="Id" OtherKey="Actividad_id" Type="Actividades_Supuesto" />
      <Association Name="Actividade_Responsables_Resultado" Member="Responsables_Resultados" ThisKey="Id" OtherKey="Actividad_id" Type="Responsables_Resultado" />
      <Association Name="Actividade_actividades_presupuesto" Member="actividades_presupuestos" ThisKey="Id" OtherKey="actividad_id" Type="actividades_presupuesto" />
      <Association Name="Actividade_Indicadore" Member="Indicadores" ThisKey="Id" OtherKey="Actividad_id" Type="Indicadore" />
      <Association Name="Subproceso_Actividade" Member="Subproceso" ThisKey="Subproceso_id" OtherKey="Id" Type="Subproceso" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Indicadores" Member="Indicadores">
    <Type Name="Indicadore">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Actividad_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Indicador" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="unidad_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="verbo_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha_indicador_inicial" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecha_indicador_final" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Fecha_Creacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SSP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="meta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="medios" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="supuestos" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Indicadore_Indicadores_Responsable" Member="Indicadores_Responsables" ThisKey="Id" OtherKey="Indicador_id" Type="Indicadores_Responsable" />
      <Association Name="Indicadore_Indicadores_Meta" Member="Indicadores_Metas" ThisKey="Id" OtherKey="Indicador_id" Type="Indicadores_Meta" />
      <Association Name="Actividade_Indicadore" Member="Actividade" ThisKey="Actividad_id" OtherKey="Id" Type="Actividade" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Verbo_Indicadore" Member="Verbo" ThisKey="verbo_id" OtherKey="Id" Type="Verbo" IsForeignKey="true" />
      <Association Name="Unidade_Indicadore" Member="Unidade" ThisKey="unidad_id" OtherKey="Id" Type="Unidade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Documentos_Proyecto" Member="Documentos_Proyectos">
    <Type Name="Documentos_Proyecto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ruta" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="proyectoid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Tamano" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Proyecto_Documentos_Proyecto" Member="Proyecto" ThisKey="proyectoid" OtherKey="Id" Type="Proyecto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Causas_Efectos" Member="Causas_Efectos">
    <Type Name="Causas_Efecto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Proyecto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Causa" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Efecto" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Proceso" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Proceso_Detalle" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Indicador_Resultado" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Presupuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Beneficios" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="CausaIndirecta" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="EfectoIndirecto" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Association Name="Causas_Efecto_Subproceso" Member="Subprocesos" ThisKey="Id" OtherKey="Proceso_id" Type="Subproceso" />
      <Association Name="Proyecto_Causas_Efecto" Member="Proyecto" ThisKey="Proyecto_id" OtherKey="Id" Type="Proyecto" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Registro_Proyectos" Member="Registro_Proyectos">
    <Type Name="Registro_Proyecto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Dependencia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Cargo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Mpp_1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Mpp_2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Mpp_3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Justificacion" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="proyecto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="responsable" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Proyecto_Registro_Proyecto" Member="Proyecto" ThisKey="proyecto_id" OtherKey="Id" Type="Proyecto" IsForeignKey="true" />
    </Type>
  </Table>
</Database>